### ISSUE TITLE
bug: frontend break to error

### ISSUE THREAD

**Issue by linxinqiang90** [uxbox/uxbox#7726]
### Steps To Reproduce

1.  wget https://raw.githubusercontent.com/penpot/penpot/main/docker/images/docker-compose.yaml
2.  docker compose up
3. visit `localhost:9001`
4. mouse over image area,get error

<img width="330" height="569" alt="Image" src="https://github.com/user-attachments/assets/9363b363-4934-4cbc-a5ae-139f0423fb25" />
<img width="403" height="128" alt="Image" src="https://github.com/user-attachments/assets/184f879f-c625-4e29-9789-9628f41c30ae" />

<img width="1506" height="1032" alt="Image" src="https://github.com/user-attachments/assets/1230070e-a664-41b8-a7b7-d0ae28ad77b9" />

### Expected behavior

```
```

### Actual behavior

bs console error:

```js
Unhandled Error
main.44bc4b7fa-1754046250.js:721 TypeError: I.hidePopover is not a function
  at main.44bc4b7fa-1754046250.js:786:190
  at QTe (libs.js?ts=1754046776119:29:117926)
  at libs.js?ts=1754046776119:29:122978
  at eSe (libs.js?ts=1754046776119:29:9069)
  at QV (libs.js?ts=1754046776119:29:119168)
  at UK (libs.js?ts=1754046776119:30:26788)
  at zIt (libs.js?ts=1754046776119:30:26701)
shared.44bc4b7fa-1754046250.js:112 {:hint "I.hidePopover is not a function"}
```

[report.txt](https://github.com/user-attachments/files/23474162/report.txt)

### Frontend Stack Trace

```console

```

### Backend Stack Trace

```console

```

**Comment by Linkk2000** [comment]
@linxinqiang90  Hi，I'm facing the same situation now. I'm working in an isolated internal network without internet access. I wonder if you have solved this problem?

**Comment by Linkk2000** [comment]
@linxinqiang90 Hello, the issue was resolved after I upgraded from Firefox 117 to 145.

**Comment by linxinqiang90** [comment]
> [@linxinqiang90](https://github.com/linxinqiang90) Hello, the issue was resolved after I upgraded from Firefox 117 to 145.

Thanks for the heads-up! Updating my Chrome engine solved the problem.
